@startuml
'https://plantuml.com/object-diagram

object "<u>characterPropertiesFactory:CharacterPropertiesFactory</u>" as characterPropertiesFactory {
    characterPropertiesMap = [
        "arial14Black" -> {font="Arial", fontSize=14, fontColor="Black"},
        "verdana18Blue" -> {font="Verdana", fontSize=18, fontColor="Blue"},
        "verdana12Red" -> {font="Verdana", fontSize=12, fontColor="Red"},
        "calibri99Blue" -> {font="Calibri", fontSize=99, fontColor="Blue"}
    ]
}

object "<u>arial14Black:CharacterProperties</u>" as arial14Black {
    font = "Arial"
    fontSize = 14
    fontColor = "Black"
}

object "<u>verdana18Blue:CharacterProperties</u>" as verdana18Blue {
    font = "Verdana"
    fontSize = 18
    fontColor = "Blue"
}

object "<u>verdana12Red:CharacterProperties</u>" as verdana12Red {
    font = "Verdana"
    fontSize = 12
    fontColor = "Red"
}

object "<u>calibri99Blue:CharacterProperties</u>" as calibri99Blue {
    font = "Calibri"
    fontSize = 99
    fontColor = "Blue"
}

object "<u>document:Document</u>" as document {
    characters = [
        {symbol='H', properties=calibri99Blue},
        {symbol='e', properties=arial14Black},
        {symbol='l', properties=arial14Black},
        {symbol='l', properties=arial14Black},
        {symbol='o', properties=arial14Black},
        {symbol='W', properties=calibri99Blue},
        {symbol='o', properties=arial14Black},
        {symbol='r', properties=arial14Black},
        {symbol='l', properties=arial14Black},
        {symbol='d', properties=arial14Black},
        {symbol='C', properties=verdana18Blue},
        {symbol='S', properties=verdana18Blue},
        {symbol='5', properties=verdana12Red},
        {symbol='8', properties=verdana12Red},
        {symbol='0', properties=verdana12Red},
        {symbol='0', properties=verdana12Red}
    ]
}

characterPropertiesFactory --o arial14Black
characterPropertiesFactory --o verdana18Blue
characterPropertiesFactory --o verdana12Red
characterPropertiesFactory --o calibri99Blue

document --o calibri99Blue : 'H', 'W'
document --o arial14Black : 'e', 'l', 'o', 'r', 'l', 'd'
document --o verdana18Blue : 'C', 'S'
document --o verdana12Red : '5', '8', '0', '0'
@enduml
